# Path to your oh-my-zsh installation.
export ZSH="/home/andriati/.oh-my-zsh"
ZSH_THEME="spaceship"
CASE_SENSITIVE="true"

# set nvim as default editor
export EDITOR=$(which nvim)

# Add wisely, as too many plugins slow down shell startup.
plugins=(
    poetry
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
)

SPACESHIP_PROMPT_ORDER=(
  pyenv
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  exec_time     # Execution time
  line_sep      # Line break
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_DIR_TRUNC=0
SPACESHIP_GIT_SYMBOL=" "
SPACESHIP_GIT_BRANCH_COLOR="#3daee9"
SPACESHIP_DIR_COLOR="#3daee9"
SPACESHIP_PYENV_SYMBOL=" "
SPACESHIP_PYENV_COLOR=198

export VIRTUAL_ENV_DISABLE_PROMPT=true

source $ZSH/oh-my-zsh.sh

#export PYENV_ROOT="$HOME/.pyenv"
#export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"
#
#eval "$(pyenv virtualenv-init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
FD_OPTIONS="--color=always --exclude __pycache__ --exclude .git --exclude Steam --exclude '*.pyc'"
export FZF_DEFAULT_COMMAND="fd --type f --type l $FD_OPTIONS"
export FZF_ALT_C_COMMAND="fd --type d $FD_OPTIONS"
alias fzfh="fd --hidden --type f --type l $FD_OPTIONS | fzf"
alias rawfzf="fd -I --hidden --type f --type l --type d | fzf"
export FZF_DEFAULT_OPTS="
  --ansi
  --layout=reverse
  --info=inline
  --height=90%
  --multi
  --preview-window=:hidden:down:80%
  --preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
  --bind '?:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo {} | xclip -sel clip)'
  --bind 'ctrl-o:execute(echo {+} | xargs xdg-open &> /dev/null &)'
  --bind 'ctrl-e:execute(echo {+} | xargs -o nvim)'
  --bind 'ctrl-f:execute-silent(realpath {} | xargs -0 dirname | xargs -0 dolphin &> /dev/null &)'
  --color='gutter:233,marker:160,hl:198,hl+:160,bg+:16,fg+:238'
  --pointer='▶'
  --marker='✓'
"

# The next line updates PATH for the Google Cloud SDK.
# if [ -f '/home/andriati/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/andriati/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/home/andriati/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/andriati/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
